\uD83D\uDD39 Configure application.properties
spring.datasource.url=jdbc:mysql://localhost:3306/career_portal
spring.datasource.username=root
spring.datasource.password=Niki@2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nikithakaranam2006@gmail.com
spring.mail.password=gjeazmesdjjelmct
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# \uD83D\uDD25 IMPORTANT (ANTI-SPAM)
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com